Admin Style Upgrade + Fully working button edit
DanielJakubek/DeepFreeze3.0 pull request #61
Opened 2022-02-03 16:32 UTC by SamHarbi

2022-02-03 16:33 UTC, ScottyDog5 reviewed
Looks good, see no reason not to merge it

2022-02-04 08:47 UTC, DanielJakubek commented on Software_Code/Admin/Admin_page.php
The logic needs comments to explain what is happening,

2022-02-04 08:50 UTC, DanielJakubek commented on Software_Code/Admin/template.php
> +<html lang="en">
What is this and what purpose does it serve? It seems to be using old map code too?

2022-02-04 08:51 UTC, DanielJakubek requested changes
Looks good apart from the lack of comments in Admin_page.php and template.php seems to serve no purpose?

2022-02-04 09:44 UTC, DanielJakubek approved these changes

2022-02-04 09:44 UTC, DanielJakubek commented
Cool, fixed the issues. Add the comments in the branch.

2022-02-04 09:44 UTC, merged